#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 0                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : fr                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=com.noctuasoftware.stellarium_free                                          # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Bivy Club                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Spot à Bivouac, une nuit au milieu des étoiles

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Bivy Clyb                                
your_link                                 :                      
your_city                                 : France
email_address                             : bivyclub@gmail.com
facebook_username                         :                                           
instagram_username                        : bivyclub
twitter_username                          : bivyclub
github_username                           : 
youtube_username                          : bivyclub
tiktok_username                           : bivyclub
bluesky_username                          : bivyclub.bsky.social
mastodon_link                             : 

# Feature List
# Replace with features relevant to your bivouac mobile application in French.

features:
  - title: Découvrez les meilleurs spots
    description: Trouvez rapidement les plus beaux emplacements de bivouac dans les Parcs Nationaux, isolés ou accessibles, en fonction de vos envies.
    fontawesome_icon_name: campground

  - title: Renseignez-vous sur la réglementation
    description: Consultez facilement les règles locales sur le bivouac, y compris les restrictions sur les drones et le feu.
    fontawesome_icon_name: balance-scale

  - title: Points d’eau
    description: Vérifiez en un coup d’œil la présence ou l’absence de points d’eau à proximité, afin de préparer votre séjour en toute sérénité.
    fontawesome_icon_name: tint

  - title: Ajoutez vos spots favoris
    description: Partagez vos emplacements préférés avec la communauté. Contribuez à enrichir la carte avec vos découvertes et bons plans.
    fontawesome_icon_name: plus-circle

  - title: Visualisation sur carte 3D
    description: Repérez votre emplacement et explorez des spots de bivouac grâce à une carte 3D intuitive. Obtenez l’altitude en quelques secondes.
    fontawesome_icon_name: map-marked-alt

  - title: Informations pratiques
    description: Consultez la saison idéale, le nombre de tentes installables, la présence d’un réseau mobile ou encore la distance des points d’eau.
    fontawesome_icon_name: info-circle

  # - title: Alertes et notifications
    # description: Recevez des alertes sur les conditions météo, les fermetures temporaires et les mises à jour réglementaires, pour une expérience sûre et optimisée.
    # fontawesome_icon_name: bell


# Theme Settings
topbar_color: "#000000"
topbar_transparency: 0.1
topbar_title_color: "#ffffff"

# Replace with your own cover image reflecting the bivouac theme.
cover_image: assets/bivouac_cover.png
cover_overlay_color: "#363b3d"
cover_overlay_transparency: 0.8

device_color: black

body_background_color: "#ffffff"

link_color: "#1d63ea"

app_title_color: "#ffffff"
app_price_color: "#ffffff"
app_description_color: "#ffffff"

feature_title_color: "#000000"
feature_text_color: "#666666"

feature_icons_foreground_color: "#1d63ea"
feature_icons_background_color: "#e6e6e6"

social_icons_foreground_color: "#666666"
social_icons_background_color: "#e6e6e6"

footer_text_color: "#666666"





####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
